import SampleImage from '../../assets/SamplePropertyImage.jpg'
import { imagesArray } from './fakeUserData';

export const Properties2 = [
  {
    id: 1,
    address: {
      streetAddress: "812",
      streetName: "46 Nairn Street",
      suburb: "Mount Cook",
      city: "Wellington",
      country: "New Zealand",
      pinCode: "6011",
    },
    propertyType: "Residential",
    area: "200 Sq. Mtr",
    price: "$ 380.00 per week",
    availableFor: "Lease",
    title:"2BHK for lease at Wellington",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.286858597134774,
      longitude: 174.7753787154708,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Ivy',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
  {
    id: 2,
    address: {
      streetAddress: "123",
      streetName: "Main Street",
      suburb: "Downtown",
      city: "Cityville",
      country: "United States",
      pinCode: "12345",
    },
    propertyType: "Commercial",
    area: "500 Sq. Mtr",
    price: "$ 1500.00 per month",
    availableFor: "Lease",
    title:"Commercial space for lease in Cityville",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.28940608045941,
      longitude: 174.77426291604044,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },

  {
    id: 3,
    address: {
      streetAddress: "456",
      streetName: "Ocean Avenue",
      suburb: "Seaside",
      city: "Beachtown",
      country: "United States",
      pinCode: "54321",
    },
    propertyType: "Residential",
    area: "150 Sq. Mtr",
    price: "$ 900.00 per week",
    availableFor: "Lease",
    title: "Cozy beachfront apartment for lease in Beachtown",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29443626172504,
      longitude: 174.78670836566965,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
  {
    id: 4,
    address: {
      streetAddress: "789",
      streetName: "Hillside Road",
      suburb: "Hillsborough",
      city: "Greenfield",
      country: "United States",
      pinCode: "98765",
    },
    propertyType: "Residential",
    area: "300 Sq. Mtr",
    price: "$ 1200.00 per month",
    availableFor: "Lease",
    title: "Spacious house with scenic views for lease in Greenfield",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29511337189054,
      longitude: 174.78074313291637,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
  {
    id: 5,
    address: {
      streetAddress: "321",
      streetName: "Garden Street",
      suburb: "Bloomingville",
      city: "Gardenia",
      country: "United States",
      pinCode: "56789",
    },
    propertyType: "Residential",
    area: "180 Sq. Mtr",
    price: "$ 800.00 per week",
    availableFor: "Lease",
    title: "Charming garden house for lease in Gardenia",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29978846455298,
      longitude: 174.78022814879378,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
  {
    id: 6,
    address: {
      streetAddress: "987",
      streetName: "Lakeview Drive",
      suburb: "Lakeside",
      city: "Watersville",
      country: "United States",
      pinCode: "45678",
    },
    propertyType: "Residential",
    area: "250 Sq. Mtr",
    price: "$ 1000.00 per month",
    availableFor: "Lease",
    title: "Lakefront house for lease in Watersville",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29534767131139,
      longitude: 174.78594540722116,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
  {
    id: 7,
    address: {
      streetAddress: "654",
      streetName: "Mountain Road",
      suburb: "Summitville",
      city: "Peaktown",
      country: "United States",
      pinCode: "87654",
    },
    propertyType: "Residential",
    area: "220 Sq. Mtr",
    price: "$ 950.00 per week",
    availableFor: "Lease",
    title: "Mountain view house for lease in Peaktown",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29274628008386,
      longitude: 174.78199538034906,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    image:SampleImage,
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:imagesArray,
  },
];


export const Properties1 = [
  {
    id: 1,
    address: {
      streetAddress: "812",
      streetName: "46 Nairn Street",
      suburb: "Mount Cook",
      city: "Wellington",
      country: "New Zealand",
      pinCode: "6011",
    },
    propertyType: "Residential",
    area: "200 Sq. Mtr",
    price: "$ 380.00 per week",
    availableFor: "Lease",
    title:"2BHK for lease at Wellington",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.286858597134774,
      longitude: 174.7753787154708,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/1/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Jessica Rodriguez',
      imageManager:'gs://homequestnz.appspot.com/managerImage/1.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'jessica.rodriguez@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/1/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/1/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/1/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/1/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/1/image5.jpg',
    ],
  },
  {
    id: 2,
    address: {
      streetAddress: "123",
      streetName: "Main Street",
      suburb: "Downtown",
      city: "Cityville",
      country: "United States",
      pinCode: "12345",
    },
    propertyType: "Commercial",
    area: "500 Sq. Mtr",
    price: "$ 1500.00 per month",
    availableFor: "Lease",
    title:"Commercial space for lease in Cityville",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.28940608045941,
      longitude: 174.77426291604044,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/2/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Kyle Bruce',
      imageManager:'gs://homequestnz.appspot.com/managerImage/2.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'kyle.bruce@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/2/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/2/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/2/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/2/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/2/image5.jpg',

    ],
  },

  {
    id: 3,
    address: {
      streetAddress: "456",
      streetName: "Ocean Avenue",
      suburb: "Seaside",
      city: "Beachtown",
      country: "United States",
      pinCode: "54321",
    },
    propertyType: "Residential",
    area: "150 Sq. Mtr",
    price: "$ 900.00 per week",
    availableFor: "Lease",
    title: "Cozy beachfront apartment for lease in Beachtown",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29443626172504,
      longitude: 174.78670836566965,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/3/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Sarah Thompson',
      imageManager:'gs://homequestnz.appspot.com/managerImage/3.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'sarah.thompson@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/3/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/3/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/3/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/3/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/3/image5.jpg',
 
    ],
  },
  {
    id: 4,
    address: {
      streetAddress: "789",
      streetName: "Hillside Road",
      suburb: "Hillsborough",
      city: "Greenfield",
      country: "United States",
      pinCode: "98765",
    },
    propertyType: "Residential",
    area: "300 Sq. Mtr",
    price: "$ 1200.00 per month",
    availableFor: "Lease",
    title: "Spacious house with scenic views for lease in Greenfield",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29511337189054,
      longitude: 174.78074313291637,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/4/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Emily Johnson',
      imageManager:'gs://homequestnz.appspot.com/managerImage/4.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'emily.johnson@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/4/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/4/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/4/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/4/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/4/image5.jpg',

    ],
  },
  {
    id: 5,
    address: {
      streetAddress: "321",
      streetName: "Garden Street",
      suburb: "Bloomingville",
      city: "Gardenia",
      country: "United States",
      pinCode: "56789",
    },
    propertyType: "Residential",
    area: "180 Sq. Mtr",
    price: "$ 800.00 per week",
    availableFor: "Lease",
    title: "Charming garden house for lease in Gardenia",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29978846455298,
      longitude: 174.78022814879378,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/5/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Benjamin Anderson',
      imageManager:'gs://homequestnz.appspot.com/managerImage/5.jpg',
      contactNo:'+64 12345678',
      email:'benjamin.anderson@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/5/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/5/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/5/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/5/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/5/image5.jpg',
    ],
  },
  {
    id: 6,
    address: {
      streetAddress: "987",
      streetName: "Lakeview Drive",
      suburb: "Lakeside",
      city: "Watersville",
      country: "United States",
      pinCode: "45678",
    },
    propertyType: "Residential",
    area: "250 Sq. Mtr",
    price: "$ 1000.00 per month",
    availableFor: "Lease",
    title: "Lakefront house for lease in Watersville",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29534767131139,
      longitude: 174.78594540722116,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/6/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Daniel Ramirez',
      imageManager:'gs://homequestnz.appspot.com/managerImage/6.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'daniel.ramirez@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/6/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/6/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/6/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/6/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/6/image5.jpg',
    ],
  },
  {
    id: 7,
    address: {
      streetAddress: "654",
      streetName: "Mountain Road",
      suburb: "Summitville",
      city: "Peaktown",
      country: "United States",
      pinCode: "87654",
    },
    propertyType: "Residential",
    area: "220 Sq. Mtr",
    price: "$ 950.00 per week",
    availableFor: "Lease",
    title: "Mountain view house for lease in Peaktown",
    description: {  
      shortDescription:'short description',
      longDescription:'Delta Lake Heights is a strong, active community which regularly gathers for social occasions and contributes a ready opportunity to go walking, cycling, sailing and kayaking. This all-encompassing lifestyle property offers the best of everything in New Zealand’s sunniest region',
    },
    gCoordinate: {
      latitude: -41.29274628008386,
      longitude: 174.78199538034906,
    },
    amenities: [
      "Lift",
      "Parking",
      "Pet Friendly",
      "Lift",
      "Parking",
      "Pet Friendly",
    ],
    imageProperty:'gs://homequestnz.appspot.com/propertyImage/7/main.jpg',
    createdOn:'26 May 2022',
    lastUpdatedOn:'1st June 2023',
    availableFrom:'Monday, 26th June 2023',
    assignManager:{
      name:'Ryan Johnson',
      imageManager:'gs://homequestnz.appspot.com/managerImage/7.jpg',
      designation:'Property Manager',
      contactNo:'+64 12345678',
      email:'ryan.johnson@gmail.com',
  },
    allImageArray:[
      'gs://homequestnz.appspot.com/propertyImage/7/image1.jpg',
      'gs://homequestnz.appspot.com/propertyImage/7/image2.jpg',
      'gs://homequestnz.appspot.com/propertyImage/7/image3.jpg',
      'gs://homequestnz.appspot.com/propertyImage/7/image4.jpg',
      'gs://homequestnz.appspot.com/propertyImage/7/image5.jpg',
      
    ],
  },
];